In [1]:
import numpy as np
import pandas as pd



In [2]:
from dataset import load_dataset, load_labels, convert_to_epochs, load_channels
from features import time_series_features, nonlinear_features, entropy_features, hjorth_features, freq_band_features
from classifiers import LR, KNN, SVM, NN
import variables as v

In [3]:
#importing ICA filtered two times

dataset_ica_2_ = load_dataset(data_type="ica2", test_type="Arithmetic")

channels = load_channels()


In [4]:
channels_1 = ['Fp1', 'C3', 'T7','O1', 'O2' 'T8', 'C4', 'Fp2']
channels_2 = ['F3', 'C3', 'P3', 'O1', 'O2', 'P4', 'C4', 'F4']
channels_3 = ['Fp1', 'C3', 'P7', 'O1', 'O2', 'P8', 'C4', 'Fp2']
channels_4 = ['Cz', 'Fz', 'P3', 'Pz', 'PO9', 'Oz', 'PO10', 'P4']

n_sub_ch = 8

In [5]:
def get_subset(data, all_channels, subset_channels):
    subset_data = np.empty((120, 8, 3200))

    j = 0
    for i in range(len(all_channels)):
        if j < (n_sub_ch + 1) and all_channels[i] in subset_channels:
            subset_data[:,j,:] = data[:,i,:]
            j+=1
    return subset_data

In [6]:
def check_nan(array):
    x = np.isnan(array)
    if True in x:
        print('NAN in array')
        return 0
    print('No NAN found')

In [7]:

subset_data_1 = get_subset(dataset_ica_2_, channels, channels_1)
subset_data_2 = get_subset(dataset_ica_2_, channels, channels_2)
subset_data_3 = get_subset(dataset_ica_2_, channels, channels_3)
subset_data_4 = get_subset(dataset_ica_2_, channels, channels_4)


check_nan(subset_data_1[0])
check_nan(subset_data_1[0])
check_nan(subset_data_1[0])


No NAN found
No NAN found
No NAN found


In [9]:
dataset_2 = convert_to_epochs(subset_data_2, n_sub_ch, v.SFREQ)
features_2 = time_series_features(dataset_2, n_sub_ch)
data_2 = features_2
check_nan(data_2)

dataset_3 = convert_to_epochs(subset_data_3, n_sub_ch, v.SFREQ)
features_3 = time_series_features(dataset_3, n_sub_ch)
data_3 = features_3
check_nan(data_3)

dataset_4 = convert_to_epochs(subset_data_4, n_sub_ch, v.SFREQ)
features_4 = time_series_features(dataset_4, n_sub_ch)
data_4 = features_4
check_nan(data_4)




(120, 25, 8, 128)
No NAN found
(120, 25, 8, 128)
No NAN found
(120, 25, 8, 128)
No NAN found


In [12]:
labels = load_labels()
label = pd.concat([labels['t1_math'], labels['t2_math'],
                  labels['t3_math']]).to_numpy()
label = label.repeat(dataset_1.shape[1])

print(np.isnan(label))

[False False False ... False False False]


### LR

In [13]:
print('Channel subset 2')
LR(data_2, label)

print('Channel subset 3')
LR(data_3, label)

print('Channel subset 4')
LR(data_4, label)



Channel subset 2
              precision    recall  f1-score   support

       False       0.59      0.62      0.61       527
        True       0.54      0.51      0.53       463

    accuracy                           0.57       990
   macro avg       0.57      0.57      0.57       990
weighted avg       0.57      0.57      0.57       990


 Confusion matrix:
[[329 198]
 [226 237]]

 Sensitivity: 0.5927927927927928

 Specificity: 0.5448275862068965
Channel subset 3
              precision    recall  f1-score   support

       False       0.56      0.60      0.58       527
        True       0.50      0.46      0.48       463

    accuracy                           0.53       990
   macro avg       0.53      0.53      0.53       990
weighted avg       0.53      0.53      0.53       990


 Confusion matrix:
[[317 210]
 [252 211]]

 Sensitivity: 0.5571177504393673

 Specificity: 0.501187648456057
Channel subset 4
              precision    recall  f1-score   support

       False       

### KNN

In [14]:
print('Channel subset 2')
KNN(data_2, label)

print('Channel subset 3')
KNN(data_3, label)

print('Channel subset 4')
KNN(data_4, label)



Channel subset 2
              precision    recall  f1-score   support

       False       0.58      0.74      0.65       311
        True       0.60      0.42      0.49       289

    accuracy                           0.58       600
   macro avg       0.59      0.58      0.57       600
weighted avg       0.59      0.58      0.57       600


 Confusion matrix:
[[231  80]
 [169 120]]

 Sensitivity: 0.5775

 Specificity: 0.6
Channel subset 3
              precision    recall  f1-score   support

       False       0.63      0.66      0.64       311
        True       0.61      0.59      0.60       289

    accuracy                           0.62       600
   macro avg       0.62      0.62      0.62       600
weighted avg       0.62      0.62      0.62       600


 Confusion matrix:
[[204 107]
 [119 170]]

 Sensitivity: 0.631578947368421

 Specificity: 0.6137184115523465
Channel subset 4
              precision    recall  f1-score   support

       False       0.65      0.65      0.65   

### SVM

In [15]:
print('Channel subset 2')
SVM(data_2, label)

print('Channel subset 3')
SVM(data_3, label)

print('Channel subset 4')
SVM(data_4, label)



Channel subset 2
              precision    recall  f1-score   support

       False       0.70      0.75      0.72       311
        True       0.71      0.66      0.68       289

    accuracy                           0.70       600
   macro avg       0.71      0.70      0.70       600
weighted avg       0.71      0.70      0.70       600


 Confusion matrix:
[[232  79]
 [ 98 191]]

 Sensitivity: 0.703030303030303

 Specificity: 0.7074074074074074
Channel subset 3
              precision    recall  f1-score   support

       False       0.75      0.78      0.76       311
        True       0.75      0.72      0.74       289

    accuracy                           0.75       600
   macro avg       0.75      0.75      0.75       600
weighted avg       0.75      0.75      0.75       600


 Confusion matrix:
[[242  69]
 [ 80 209]]

 Sensitivity: 0.7515527950310559

 Specificity: 0.7517985611510791
Channel subset 4
              precision    recall  f1-score   support

       False       