In [19]:
import numpy as np
import pandas as pd



In [20]:
from dataset import load_dataset, load_labels, convert_to_epochs, load_channels
from features import time_series_features, nonlinear_features, entropy_features, hjorth_features, freq_band_features
from classifiers import LR, KNN, SVM, NN
import variables as v

In [22]:
#importing ICA filtered two times

dataset_ica_2_ = load_dataset(data_type="ica2", test_type="Arithmetic")

channels = load_channels()

print(channels)

['Cz', 'Fz', 'Fp1', 'F7', 'F3', 'FC1', 'C3', 'FC5', 'FT9', 'T7', 'CP5', 'CP1', 'P3', 'P7', 'PO9', 'O1', 'Pz', 'Oz', 'O2', 'PO10', 'P8', 'P4', 'CP2', 'CP6', 'T8', 'FT10', 'FC6', 'C4', 'FC2', 'F4', 'F8', 'Fp2']


In [26]:
channels_1 = ['Fp1', 'C3', 'T7','O1', 'O2' 'T8', 'C4', 'Fp2']
channels_2 = ['F3', 'C3', 'P3', 'O1', 'O2', 'P4', 'C4', 'F4']
channels_3 = ['Fp1', 'C3', 'P7', 'O1', 'O2', 'P8', 'C4', 'Fp2']
channels_4 = ['Cz', 'Fz', 'P3', 'Pz', 'O1', 'Oz', 'O2', 'P4']
channels_5 = ['Cz', 'Fz', 'T7', 'P3', 'O1', 'O2', 'P4', 'T8']
channels_6 = ['F7', 'T7', 'P7', 'O1', 'O2', 'P8', 'T8', 'F8']
channels_7 = ['F7', 'F3', 'P3', 'P7', 'P8', 'P4', 'F4', 'F8']
channels_8 = ['Cz', 'F3', 'C3', 'O1', 'Pz', 'O2', 'C4', 'F4']

n_sub_ch = 8

In [23]:
def get_subset(data, all_channels, subset_channels):
    subset_data = np.empty((120, 8, 3200))

    j = 0
    for i in range(len(all_channels)):
        if j < (n_sub_ch + 1) and all_channels[i] in subset_channels:
            subset_data[:,j,:] = data[:,i,:]
            j+=1
    return subset_data

In [24]:
def check_nan(array):
    x = np.isnan(array)
    if True in x:
        print('NAN in array')
        return 0
    print('No NAN found')

In [27]:

subset_data_1 = get_subset(dataset_ica_2_, channels, channels_1)
subset_data_2 = get_subset(dataset_ica_2_, channels, channels_2)
subset_data_3 = get_subset(dataset_ica_2_, channels, channels_3)
subset_data_4 = get_subset(dataset_ica_2_, channels, channels_4)

subset_data_5 = get_subset(dataset_ica_2_, channels, channels_5)
subset_data_6 = get_subset(dataset_ica_2_, channels, channels_6)
subset_data_7 = get_subset(dataset_ica_2_, channels, channels_7)
subset_data_8 = get_subset(dataset_ica_2_, channels, channels_8)


In [28]:
dataset_2 = convert_to_epochs(subset_data_2, n_sub_ch, v.SFREQ)
features_2 = time_series_features(dataset_2, n_sub_ch)
data_2 = features_2
check_nan(data_2)

dataset_3 = convert_to_epochs(subset_data_3, n_sub_ch, v.SFREQ)
features_3 = time_series_features(dataset_3, n_sub_ch)
data_3 = features_3
check_nan(data_3)

dataset_4 = convert_to_epochs(subset_data_4, n_sub_ch, v.SFREQ)
features_4 = time_series_features(dataset_4, n_sub_ch)
data_4 = features_4
check_nan(data_4)

dataset_5 = convert_to_epochs(subset_data_5, n_sub_ch, v.SFREQ)
features_5 = time_series_features(dataset_5, n_sub_ch)
data_5 = features_5
check_nan(data_5)

dataset_6 = convert_to_epochs(subset_data_6, n_sub_ch, v.SFREQ)
features_6 = time_series_features(dataset_6, n_sub_ch)
data_6 = features_6
check_nan(data_6)

dataset_7 = convert_to_epochs(subset_data_7, n_sub_ch, v.SFREQ)
features_7 = time_series_features(dataset_7, n_sub_ch)
data_7 = features_7
check_nan(data_7)

dataset_8 = convert_to_epochs(subset_data_8, n_sub_ch, v.SFREQ)
features_8 = time_series_features(dataset_8, n_sub_ch)
data_8 = features_8
check_nan(data_8)






(120, 25, 8, 128)
No NAN found
(120, 25, 8, 128)
No NAN found
(120, 25, 8, 128)
No NAN found
(120, 25, 8, 128)
No NAN found
(120, 25, 8, 128)
No NAN found
(120, 25, 8, 128)
No NAN found
(120, 25, 8, 128)
No NAN found


In [37]:
labels = load_labels()
label = pd.concat([labels['t1_math'], labels['t2_math'],
                  labels['t3_math']]).to_numpy()
label = label.repeat(dataset_1.shape[1])

print(np.isnan(label))
print(label.shape)

[False False False ... False False False]
(3000,)


### LR

In [30]:
print('Channel subset 2')
LR(data_2, label)

print('Channel subset 3')
LR(data_3, label)

print('Channel subset 4')
LR(data_4, label)

print('Channel subset 5')
LR(data_5, label)

print('Channel subset 6')
LR(data_6, label)

print('Channel subset 7')
LR(data_7, label)

print('Channel subset 8')
LR(data_8, label)




Channel subset 2
              precision    recall  f1-score   support

       False       0.59      0.62      0.61       527
        True       0.54      0.51      0.53       463

    accuracy                           0.57       990
   macro avg       0.57      0.57      0.57       990
weighted avg       0.57      0.57      0.57       990


 Confusion matrix:
[[329 198]
 [226 237]]

 Sensitivity: 0.5927927927927928

 Specificity: 0.5448275862068965
Channel subset 3
              precision    recall  f1-score   support

       False       0.56      0.60      0.58       527
        True       0.50      0.46      0.48       463

    accuracy                           0.53       990
   macro avg       0.53      0.53      0.53       990
weighted avg       0.53      0.53      0.53       990


 Confusion matrix:
[[317 210]
 [252 211]]

 Sensitivity: 0.5571177504393673

 Specificity: 0.501187648456057
Channel subset 4
              precision    recall  f1-score   support

       False       

### KNN

In [31]:
print('Channel subset 2')
KNN(data_2, label)

print('Channel subset 3')
KNN(data_3, label)

print('Channel subset 4')
KNN(data_4, label)

print('Channel subset 5')
KNN(data_5, label)

print('Channel subset 6')
KNN(data_6, label)

print('Channel subset 7')
KNN(data_7, label)

print('Channel subset 8')
KNN(data_8, label)




Channel subset 2
              precision    recall  f1-score   support

       False       0.58      0.74      0.65       311
        True       0.60      0.42      0.49       289

    accuracy                           0.58       600
   macro avg       0.59      0.58      0.57       600
weighted avg       0.59      0.58      0.57       600


 Confusion matrix:
[[231  80]
 [169 120]]

 Sensitivity: 0.5775

 Specificity: 0.6
Channel subset 3
              precision    recall  f1-score   support

       False       0.63      0.66      0.64       311
        True       0.61      0.59      0.60       289

    accuracy                           0.62       600
   macro avg       0.62      0.62      0.62       600
weighted avg       0.62      0.62      0.62       600


 Confusion matrix:
[[204 107]
 [119 170]]

 Sensitivity: 0.631578947368421

 Specificity: 0.6137184115523465
Channel subset 4
              precision    recall  f1-score   support

       False       0.59      0.75      0.66   

### SVM

In [32]:
print('Channel subset 2')
SVM(data_2, label)

print('Channel subset 3')
SVM(data_3, label)

print('Channel subset 4')
SVM(data_4, label)

print('Channel subset 5')
SVM(data_5, label)

print('Channel subset 6')
SVM(data_6, label)

print('Channel subset 7')
SVM(data_7, label)

print('Channel subset 8')
SVM(data_8, label)



Channel subset 2
              precision    recall  f1-score   support

       False       0.70      0.75      0.72       311
        True       0.71      0.66      0.68       289

    accuracy                           0.70       600
   macro avg       0.71      0.70      0.70       600
weighted avg       0.71      0.70      0.70       600


 Confusion matrix:
[[232  79]
 [ 98 191]]

 Sensitivity: 0.703030303030303

 Specificity: 0.7074074074074074
Channel subset 3
              precision    recall  f1-score   support

       False       0.75      0.78      0.76       311
        True       0.75      0.72      0.74       289

    accuracy                           0.75       600
   macro avg       0.75      0.75      0.75       600
weighted avg       0.75      0.75      0.75       600


 Confusion matrix:
[[242  69]
 [ 80 209]]

 Sensitivity: 0.7515527950310559

 Specificity: 0.7517985611510791
Channel subset 4
              precision    recall  f1-score   support

       False       

In [33]:
print('Channel subset 2')
NN(data_2, label)


Trial 5 Complete [00h 00m 19s]
val_accuracy: 0.6991666555404663

Best val_accuracy So Far: 0.6991666555404663
Total elapsed time: 00h 01m 32s
INFO:tensorflow:Oracle triggered exit
19/19 [==============================] - 0s 888us/step
              precision    recall  f1-score   support

           0       0.66      0.78      0.72       311
           1       0.71      0.57      0.63       289

    accuracy                           0.68       600
   macro avg       0.69      0.68      0.68       600
weighted avg       0.69      0.68      0.68       600

[[244  67]
 [124 165]]


In [34]:
print('Channel subset 3')
NN(data_3, label)

Trial 5 Complete [00h 00m 19s]
val_accuracy: 0.7216666638851166

Best val_accuracy So Far: 0.7216666638851166
Total elapsed time: 00h 01m 31s
INFO:tensorflow:Oracle triggered exit
19/19 [==============================] - 0s 1ms/step
              precision    recall  f1-score   support

           0       0.75      0.66      0.70       311
           1       0.68      0.77      0.72       289

    accuracy                           0.71       600
   macro avg       0.72      0.71      0.71       600
weighted avg       0.72      0.71      0.71       600

[[205 106]
 [ 67 222]]


In [35]:
print('Channel subset 4')
NN(data_4, label)

Trial 5 Complete [00h 00m 17s]
val_accuracy: 0.5975000262260437

Best val_accuracy So Far: 0.6358333230018616
Total elapsed time: 00h 01m 29s
INFO:tensorflow:Oracle triggered exit
19/19 [==============================] - 0s 1ms/step
              precision    recall  f1-score   support

           0       0.61      0.81      0.70       311
           1       0.69      0.45      0.54       289

    accuracy                           0.64       600
   macro avg       0.65      0.63      0.62       600
weighted avg       0.65      0.64      0.62       600

[[253  58]
 [160 129]]


In [36]:
print('Channel subset 5')
NN(data_5, label)

Trial 5 Complete [00h 00m 15s]
val_accuracy: 0.6966666579246521

Best val_accuracy So Far: 0.6991666555404663
Total elapsed time: 00h 01m 23s
INFO:tensorflow:Oracle triggered exit


19/19 [==============================] - 0s 887us/step
              precision    recall  f1-score   support

           0       0.67      0.83      0.74       311
           1       0.75      0.55      0.64       289

    accuracy                           0.70       600
   macro avg       0.71      0.69      0.69       600
weighted avg       0.71      0.70      0.69       600

[[258  53]
 [129 160]]


In [38]:
print('Channel subset 6')
NN(data_6, label)

Trial 5 Complete [00h 00m 17s]
val_accuracy: 0.6616666615009308

Best val_accuracy So Far: 0.7116666436195374
Total elapsed time: 00h 01m 21s
INFO:tensorflow:Oracle triggered exit


19/19 [==============================] - 0s 887us/step
              precision    recall  f1-score   support

           0       0.69      0.81      0.74       311
           1       0.75      0.61      0.67       289

    accuracy                           0.71       600
   macro avg       0.72      0.71      0.71       600
weighted avg       0.72      0.71      0.71       600

[[251  60]
 [113 176]]


In [39]:
print('Channel subset 7')
NN(data_7, label)

Trial 5 Complete [00h 00m 18s]
val_accuracy: 0.6566666662693024

Best val_accuracy So Far: 0.6816666722297668
Total elapsed time: 00h 01m 26s
INFO:tensorflow:Oracle triggered exit
19/19 [==============================] - 0s 1ms/step
              precision    recall  f1-score   support

           0       0.68      0.77      0.72       311
           1       0.71      0.61      0.66       289

    accuracy                           0.69       600
   macro avg       0.69      0.69      0.69       600
weighted avg       0.69      0.69      0.69       600

[[239  72]
 [113 176]]


In [41]:
print('Channel subset 8')
NN(data_8, label)

Trial 5 Complete [00h 00m 17s]
val_accuracy: 0.6333333253860474

Best val_accuracy So Far: 0.6558333337306976
Total elapsed time: 00h 01m 24s
INFO:tensorflow:Oracle triggered exit
19/19 [==============================] - 0s 1ms/step
              precision    recall  f1-score   support

           0       0.65      0.78      0.71       311
           1       0.70      0.55      0.61       289

    accuracy                           0.67       600
   macro avg       0.68      0.67      0.66       600
weighted avg       0.68      0.67      0.66       600

[[244  67]
 [131 158]]
