In [1]:
import numpy as np
import pandas as pd


In [2]:
from dataset import load_dataset, load_labels, convert_to_epochs, load_channels
from features import time_series_features, nonlinear_features, entropy_features, hjorth_features, freq_band_features
from classifiers import LR, KNN, SVM, NN
import variables as v

In [3]:
#Filtered from SAM40
dataset_ = load_dataset(data_type="filtered", test_type="Arithmetic")
dataset = convert_to_epochs(dataset_, v.NUM_CHANNELS, v.SFREQ)

#ICA filtered
dataset_ica_ = load_dataset(data_type="ica1", test_type="Arithmetic")
dataset_ica = convert_to_epochs(dataset_ica_, v.NUM_CHANNELS, v.SFREQ)

#ICA filtered two times
dataset_ica_2_ = load_dataset(data_type="ica2", test_type="Arithmetic")
dataset_ica_2 = convert_to_epochs(dataset_ica_2_, v.NUM_CHANNELS, v.SFREQ)

In [4]:
features = time_series_features(dataset, v.NUM_CHANNELS)
features_ica = time_series_features(dataset_ica, v.NUM_CHANNELS)
features_ica_2 = time_series_features(dataset_ica_2, v.NUM_CHANNELS)
# freq_bands = np.array([1, 4, 8, 13, 31, 50])
# features = freq_band_features(dataset, channels, sfreq, freq_bands)
# features = nonlinear_features(dataset, channels)
# features = hjorth_features(dataset, channels, sfreq)
# features = entropy_features(dataset, channels, sfreq)
data = features
data_ica = features_ica
data_ica_2 = features_ica_2

(120, 25, 32, 128)
(120, 25, 32, 128)
(120, 25, 32, 128)


In [5]:
labels = load_labels()
label = pd.concat([labels['t1_math'], labels['t2_math'],
                  labels['t3_math']]).to_numpy()
label = label.repeat(dataset.shape[1])

### Linear Regression

In [7]:
print('Filtered data')
LR(data,label)
print('\nICA filtered data')
LR(data_ica,label)
print('\nICA filtered data round 2')
LR(data_ica_2,label)

Filtered data
              precision    recall  f1-score   support

       False       0.71      0.69      0.70       527
        True       0.66      0.67      0.66       463

    accuracy                           0.68       990
   macro avg       0.68      0.68      0.68       990
weighted avg       0.68      0.68      0.68       990


 Confusion matrix:
[[364 163]
 [152 311]]

 Sensitivity: 0.7054263565891473

 Specificity: 0.6561181434599156

ICA filtered data
              precision    recall  f1-score   support

       False       0.62      0.60      0.61       527
        True       0.56      0.58      0.57       463

    accuracy                           0.59       990
   macro avg       0.59      0.59      0.59       990
weighted avg       0.59      0.59      0.59       990


 Confusion matrix:
[[314 213]
 [193 270]]

 Sensitivity: 0.6193293885601578

 Specificity: 0.5590062111801242

ICA filtered data round 2
              precision    recall  f1-score   support

       Fa

### KNN

In [7]:
print('Filtered data')
KNN(data,label)
print('\nICA filtered data')
KNN(data_ica,label)
print('\nICA filtered data round 2')
KNN(data_ica_2,label)

Filtered data
              precision    recall  f1-score   support

       False       0.79      0.77      0.78       311
        True       0.76      0.78      0.77       289

    accuracy                           0.78       600
   macro avg       0.77      0.78      0.77       600
weighted avg       0.78      0.78      0.78       600


 Confusion matrix:
[[241  70]
 [ 65 224]]

 Sensitivity: 0.7875816993464052

 Specificity: 0.7619047619047619

ICA filtered data
              precision    recall  f1-score   support

       False       0.63      0.65      0.64       311
        True       0.61      0.59      0.60       289

    accuracy                           0.62       600
   macro avg       0.62      0.62      0.62       600
weighted avg       0.62      0.62      0.62       600


 Confusion matrix:
[[202 109]
 [118 171]]

 Sensitivity: 0.63125

 Specificity: 0.6107142857142858

ICA filtered data round 2
              precision    recall  f1-score   support

       False       0

### SVM

In [8]:
print('Filtered data')
SVM(data,label)
print('\nICA filtered data')
SVM(data_ica,label)
print('\nICA filtered data round 2')
SVM(data_ica_2,label)

Filtered data
              precision    recall  f1-score   support

       False       0.97      0.95      0.96       311
        True       0.95      0.97      0.96       289

    accuracy                           0.96       600
   macro avg       0.96      0.96      0.96       600
weighted avg       0.96      0.96      0.96       600


 Confusion matrix:
[[296  15]
 [ 10 279]]

 Sensitivity: 0.9673202614379085

 Specificity: 0.9489795918367347

ICA filtered data
              precision    recall  f1-score   support

       False       0.70      0.84      0.76       311
        True       0.78      0.61      0.68       289

    accuracy                           0.73       600
   macro avg       0.74      0.73      0.72       600
weighted avg       0.74      0.73      0.73       600


 Confusion matrix:
[[262  49]
 [113 176]]

 Sensitivity: 0.6986666666666667

 Specificity: 0.7822222222222223

ICA filtered data round 2
              precision    recall  f1-score   support

       Fa

# Neural Network

In [6]:
print('Filtered data')
NN(data,label)
print('\nICA filtered data')
NN(data_ica,label)
print('\nICA filtered data round 2')
NN(data_ica_2,label)

Trial 2 Complete [00h 00m 16s]
val_accuracy: 0.6525000035762787

Best val_accuracy So Far: 0.6525000035762787
Total elapsed time: 00h 00m 38s

Search: Running Trial #3

Value             |Best Value So Far |Hyperparameter
4                 |4                 |layers
864               |32                |units_0
sigmoid           |relu              |act_0
0.0001            |0.0001            |learning_rate

Epoch 1/50
57/57 [==============================] - 1s 7ms/step - loss: 0.6714 - accuracy: 0.5867 - val_loss: 0.6433 - val_accuracy: 0.6550
Epoch 2/50
57/57 [==============================] - 0s 4ms/step - loss: 0.6327 - accuracy: 0.6722 - val_loss: 0.6158 - val_accuracy: 0.7167
Epoch 3/50
57/57 [==============================] - 0s 3ms/step - loss: 0.6113 - accuracy: 0.7239 - val_loss: 0.6123 - val_accuracy: 0.6933
Epoch 4/50
57/57 [==============================] - 0s 4ms/step - loss: 0.6002 - accuracy: 0.7217 - val_loss: 0.5934 - val_accuracy: 0.7467
Epoch 5/50
57/57 [============

FailedPreconditionError: Failed to rename: .\untitled_project\trial_2\checkpoint_temp/part-00000-of-00001.data-00000-of-00001 to: .\untitled_project\trial_2\checkpoint.data-00000-of-00001 : Prosessen får ikke tilgang til filen fordi den brukes av en annen prosess.
; Broken pipe [Op:MergeV2Checkpoints]