In [1]:
import numpy as np
import pandas as pd


In [2]:
from dataset import load_dataset, load_labels, convert_to_epochs, load_channels
from features import time_series_features, fractal_features, entropy_features, hjorth_features, freq_band_features
from classifiers import KNN, SVM, NN
import variables as v

In [3]:
#RAW
dataset_RAW_ = load_dataset(data_type="raw", test_type="Arithmetic")
dataset_RAW = convert_to_epochs(dataset_RAW_, v.NUM_CHANNELS, v.SFREQ)

#WT filtered
dataset_WT_ = load_dataset(data_type="filtered", test_type="Arithmetic")
dataset_WT = convert_to_epochs(dataset_WT_, v.NUM_CHANNELS, v.SFREQ)

#one-time ICA
dataset_ICA_ = load_dataset(data_type="ica1", test_type="Arithmetic")
dataset_ICA = convert_to_epochs(dataset_ICA_, v.NUM_CHANNELS, v.SFREQ)

#two-times ICA
dataset_ICA_2_ = load_dataset(data_type="ica2", test_type="Arithmetic")
dataset_ICA_2 = convert_to_epochs(dataset_ICA_2_, v.NUM_CHANNELS, v.SFREQ)

In [4]:
# time series features
freq_bands = np.array([1, 4, 8, 12, 30, 50])

data_RAW = freq_band_features(dataset_RAW, v.NUM_CHANNELS, v.SFREQ, freq_bands)
data_WT = freq_band_features(dataset_WT, v.NUM_CHANNELS, v.SFREQ, freq_bands)
data_ICA = freq_band_features(dataset_ICA, v.NUM_CHANNELS, v.SFREQ, freq_bands)
data_ICA_2 = freq_band_features(dataset_ICA_2, v.NUM_CHANNELS, v.SFREQ, freq_bands)

In [5]:
labels = load_labels()

label = pd.concat([labels['t1_math'], labels['t2_math'],
                  labels['t3_math']]).to_numpy()
print(label)
print(label.shape)
label = np.repeat(label, data_RAW.shape[0]//label.shape[0])

print(label.shape)

[ True False False False  True False False False False False  True False
 False False  True False  True  True False  True  True  True False False
 False  True False  True  True  True  True False False False  True False
  True  True  True False  True False False False False False False  True
 False False  True False False  True  True False  True False False  True
  True  True False False False  True False  True  True  True  True False
 False False False False False False False False False  True  True  True
 False  True  True False  True  True False  True False  True  True  True
  True  True False  True  True  True  True False False False False  True
  True  True  True  True  True False False False  True False  True False]
(120,)
(3000,)


### KNN

In [6]:
print('Raw data')
print(KNN(data_RAW,label))

Raw data
(3000, 160)

 Confusion matrix:
[[176 135]
 [139 150]]
[54.33 55.87 52.63]


In [7]:
print('WT data')
print(KNN(data_WT,label))

WT data
(3000, 160)

 Confusion matrix:
[[168 143]
 [154 135]]
[50.5  52.17 48.56]


In [8]:
print('\nICA filtered data')
print(KNN(data_ICA,label))



ICA filtered data
(3000, 160)

 Confusion matrix:
[[183 128]
 [140 149]]
[55.33 56.66 53.79]


In [9]:
print('\nICA filtered data round 2')
print(KNN(data_ICA_2,label))


ICA filtered data round 2
(3000, 160)

 Confusion matrix:
[[224  87]
 [164 125]]
[58.17 57.73 58.96]


### SVM

In [10]:
print('Raw data')
print(SVM(data_RAW,label))


Raw data

 Confusion matrix:
[[217  94]
 [138 151]]
[61.33 61.13 61.63]


In [18]:
print('WT data')
print(SVM(data_WT,label))

WT data

 Confusion matrix:
[[189 122]
 [134 155]]
[57.33 58.51 55.96]


In [12]:
print('\nICA filtered data')
print(SVM(data_ICA,label))



ICA filtered data

 Confusion matrix:
[[193 118]
 [150 139]]
[55.33 56.27 54.09]


In [13]:
print('\nICA filtered data round 2')
print(SVM(data_ICA_2,label))


ICA filtered data round 2

 Confusion matrix:
[[219  92]
 [141 148]]
[61.17 60.83 61.67]


# Neural Network

In [14]:
#print('RAW data')
#NN(data_RAW,label)


In [15]:
#print('WT data')
#NN(data_WT,label)


In [16]:
#print('\nICA filtered data')
#NN(data_ICA,label)


In [17]:
#print('\nICA filtered data round 2')
#NN(data_ICA_2,label)