In [1]:
import numpy as np
import pandas as pd


In [2]:
from dataset import load_dataset, load_labels, convert_to_epochs, load_channels
from features import time_series_features, fractal_features, entropy_features, hjorth_features, freq_band_features
from classifiers import KNN, SVM, NN
import variables as v

In [3]:
#RAW
dataset_RAW_ = load_dataset(data_type="raw", test_type="Arithmetic")
dataset_RAW = convert_to_epochs(dataset_RAW_, v.NUM_CHANNELS, v.SFREQ)

#WT filtered
dataset_WT_ = load_dataset(data_type="filtered", test_type="Arithmetic")
dataset_WT = convert_to_epochs(dataset_WT_, v.NUM_CHANNELS, v.SFREQ)

#one-time ICA
dataset_ICA_ = load_dataset(data_type="ica1", test_type="Arithmetic")
dataset_ICA = convert_to_epochs(dataset_ICA_, v.NUM_CHANNELS, v.SFREQ)

#two-times ICA
dataset_ICA_2_ = load_dataset(data_type="ica2", test_type="Arithmetic")
dataset_ICA_2 = convert_to_epochs(dataset_ICA_2_, v.NUM_CHANNELS, v.SFREQ)

In [4]:
# time series features
data_RAW = fractal_features(dataset_RAW, v.NUM_CHANNELS)
data_WT = fractal_features(dataset_WT, v.NUM_CHANNELS)
data_ICA = fractal_features(dataset_ICA, v.NUM_CHANNELS)
data_ICA_2 = fractal_features(dataset_ICA_2, v.NUM_CHANNELS)

In [26]:
labels = load_labels()

label = pd.concat([labels['t1_math'], labels['t2_math'],
                  labels['t3_math']]).to_numpy()
print(label)
print(label.shape)
label = np.repeat(label, data_RAW.shape[0]//label.shape[0])

print(label.shape)

[ True False False False  True False False False False False  True False
 False False  True False  True  True False  True  True  True False False
 False  True False  True  True  True  True False False False  True False
  True  True  True False  True False False False False False False  True
 False False  True False False  True  True False  True False False  True
  True  True False False False  True False  True  True  True  True False
 False False False False False False False False False  True  True  True
 False  True  True False  True  True False  True False  True  True  True
  True  True False  True  True  True  True False False False False  True
  True  True  True  True  True False False False  True False  True False]
(120,)
(3000,)


### KNN

In [28]:
print(data_RAW.shape)
print(label.shape)

(3000, 96)
(3000,)


In [36]:
print('Raw data')
print(KNN(data_RAW,label))

Raw data
(3000, 96)

 Confusion matrix:
[[199 112]
 [113 176]]
[0.625      0.63782051 0.61111111]


In [31]:
print('WT data')
print(KNN(data_WT,label))

WT data
(3000, 96)

 Confusion matrix:
[[288  23]
 [ 20 269]]
[0.92833333 0.93506494 0.92123288]


In [37]:
print('\nICA filtered data')
print(KNN(data_ICA,label))



ICA filtered data
(3000, 96)

 Confusion matrix:
[[234  77]
 [ 76 213]]
[0.745      0.75483871 0.73448276]


In [34]:
print('\nICA filtered data round 2')
print(KNN(data_ICA_2,label))


ICA filtered data round 2
(3000, 96)

 Confusion matrix:
[[278  33]
 [ 36 253]]
[0.885      0.88535032 0.88461538]


### SVM

In [39]:
print('Raw data')
print(SVM(data_RAW,label))


Raw data

 Confusion matrix:
[[259  52]
 [181 108]]
[0.61166667 0.58863636 0.675     ]


In [40]:
print('WT data')
print(SVM(data_WT,label))

WT data

 Confusion matrix:
[[297  14]
 [ 23 266]]
[0.93833333 0.928125   0.95      ]


In [41]:
print('\nICA filtered data')
print(SVM(data_ICA,label))



ICA filtered data

 Confusion matrix:
[[241  70]
 [ 64 225]]
[0.77666667 0.79016393 0.76271186]


In [42]:
print('\nICA filtered data round 2')
print(SVM(data_ICA_2,label))


ICA filtered data round 2

 Confusion matrix:
[[274  37]
 [ 46 243]]
[0.86166667 0.85625    0.86785714]


# Neural Network

In [43]:
#print('RAW data')
#NN(data_RAW,label)


Trial 1 Complete [00h 00m 24s]
val_accuracy: 0.574999988079071

Best val_accuracy So Far: 0.574999988079071
Total elapsed time: 00h 00m 24s

Search: Running Trial #2

Value             |Best Value So Far |Hyperparameter
6                 |4                 |layers
896               |960               |units_0
sigmoid           |relu              |act_0
0.0001            |0.01              |learning_rate

Epoch 1/50
57/57 [==============================] - 2s 10ms/step - loss: 0.7271 - accuracy: 0.4794 - val_loss: 0.6962 - val_accuracy: 0.5367
Epoch 2/50
57/57 [==============================] - 0s 4ms/step - loss: 0.6907 - accuracy: 0.5483 - val_loss: 0.6916 - val_accuracy: 0.5383
Epoch 3/50
57/57 [==============================] - 0s 4ms/step - loss: 0.6766 - accuracy: 0.5794 - val_loss: 0.6897 - val_accuracy: 0.5467
Epoch 4/50
57/57 [==============================] - 0s 5ms/step - loss: 0.6679 - accuracy: 0.6089 - val_loss: 0.6859 - val_accuracy: 0.5633
Epoch 5/50
57/57 [=============

FailedPreconditionError: {{function_node __wrapped__MergeV2Checkpoints_device_/job:localhost/replica:0/task:0/device:CPU:0}} Failed to rename: .\untitled_project\trial_1\checkpoint_temp/part-00000-of-00001.data-00000-of-00001 to: .\untitled_project\trial_1\checkpoint.data-00000-of-00001 : Prosessen får ikke tilgang til filen fordi den brukes av en annen prosess.
; Broken pipe [Op:MergeV2Checkpoints]

In [ ]:
#print('WT data')
#NN(data_WT,label)


In [ ]:
#print('\nICA filtered data')
#NN(data_ICA,label)


In [ ]:
#print('\nICA filtered data round 2')
#NN(data_ICA_2,label)